---
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --verbose
    ports:
      - 4000:4000  
    # A simple healthcheck to tell Docker that the site is up and running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/srv/jekyll  # Mount the project into the pwd of the Docker container

